name: app_postos
description: MVP funcional do aplicativo Grupo WK.
publish_to: "none"
version: 1.0.0+7

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  crypto: ^3.0.6
  qr_flutter: ^4.1.0
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/wk_app_icon.png
    - assets/images/home_banner.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/wk_app_icon.png"
  adaptive_icon_background: "#020712"
  adaptive_icon_foreground: "assets/images/wk_app_icon.png"
