name: app_postos
description: MVP funcional do aplicativo WK Cliente.
publish_to: "none"
version: 1.0.0+7

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  crypto: ^3.0.6
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
