from pathlib import Path

path = Path('lib/main.dart')
text = path.read_text(encoding='utf-8')

# Remove any previously injected points card from the scrollable Home content.
card_call_start = text.find("              _PointsCard(\n                pontosUsuario: app.points,")
if card_call_start != -1:
    block_start = text.rfind("              const SizedBox(height: 18),\n", 0, card_call_start + 1)
    block_end_marker = "              const SizedBox(height: 22),\n"
    block_end = text.find(block_end_marker, card_call_start)
    if block_start != -1 and block_end != -1:
        block_end += len(block_end_marker)
        text = text[:block_start] + text[block_end:]

# Give the end of the Home scroll a little breathing room. The Scaffold already
# reserves the fixed bottomNavigationBar height, so content will not sit under it.
text = text.replace(
    "padding: const EdgeInsets.fromLTRB(14, 10, 14, 20),",
    "padding: const EdgeInsets.fromLTRB(14, 10, 14, 30),",
    1,
)

# Replace the temporary compact points strip generated by refine_home_details.py
# with one fixed full points banner immediately above the Bottom Navigation.
old_bottom = r'''        bottomNavigationBar: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            AnimatedBuilder(
              animation: AppController.instance,
              builder: (context, _) {
                final points = AppController.instance.points;
                return InkWell(
                  onTap: () => Navigator.push(
                    context,
                    MaterialPageRoute(builder: (_) => const HistoryScreen()),
                  ),
                  child: Container(
                    width: double.infinity,
                    padding: const EdgeInsets.symmetric(horizontal: 18, vertical: 10),
                    decoration: const BoxDecoration(
                      gradient: LinearGradient(
                        colors: [Color(0xFF0D2D78), Color(0xFF071A45)],
                      ),
                      border: Border(
                        top: BorderSide(color: AppColors.red, width: 1.2),
                      ),
                    ),
                    child: Row(
                      children: [
                        const Icon(Icons.stars_rounded, color: Colors.white, size: 24),
                        const SizedBox(width: 10),
                        const Text(
                          'Seus pontos',
                          style: TextStyle(color: AppColors.muted, fontSize: 12),
                        ),
                        const SizedBox(width: 10),
                        Text(
                          '$points',
                          style: const TextStyle(fontSize: 22, fontWeight: FontWeight.w900),
                        ),
                        const Spacer(),
                        const Text(
                          'Ver extrato',
                          style: TextStyle(color: Colors.white, fontSize: 12, fontWeight: FontWeight.w700),
                        ),
                        const SizedBox(width: 4),
                        const Icon(Icons.chevron_right_rounded, size: 20),
                      ],
                    ),
                  ),
                );
              },
            ),
            NavigationBar(
              selectedIndex: index,
              onDestinationSelected: navigate,
              destinations: const [
                NavigationDestination(
                  icon: Icon(Icons.home_outlined),
                  selectedIcon: Icon(Icons.home_rounded),
                  label: 'Início',
                ),
                NavigationDestination(
                  icon: Icon(Icons.local_gas_station_outlined),
                  selectedIcon: Icon(Icons.local_gas_station_rounded),
                  label: 'Postos',
                ),
                NavigationDestination(
                  icon: Icon(Icons.star_border_rounded),
                  selectedIcon: Icon(Icons.star_rounded),
                  label: 'Benefícios',
                ),
                NavigationDestination(
                  icon: Icon(Icons.person_outline),
                  selectedIcon: Icon(Icons.person_rounded),
                  label: 'Perfil',
                ),
              ],
            ),
          ],
        ),'''

new_bottom = r'''        bottomNavigationBar: AnimatedBuilder(
          animation: AppController.instance,
          builder: (context, _) {
            final points = AppController.instance.points;
            return Material(
              color: const Color(0xFF020712),
              child: SafeArea(
                top: false,
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Padding(
                      padding: const EdgeInsets.fromLTRB(10, 8, 10, 6),
                      child: _PointsCard(
                        pontosUsuario: points,
                        metaProximoBeneficio: _nextBenefitGoal(points),
                        onViewStatement: () => Navigator.push(
                          context,
                          MaterialPageRoute(builder: (_) => const HistoryScreen()),
                        ),
                      ),
                    ),
                    NavigationBar(
                      selectedIndex: index,
                      onDestinationSelected: navigate,
                      destinations: const [
                        NavigationDestination(
                          icon: Icon(Icons.home_outlined),
                          selectedIcon: Icon(Icons.home_rounded),
                          label: 'Início',
                        ),
                        NavigationDestination(
                          icon: Icon(Icons.local_gas_station_outlined),
                          selectedIcon: Icon(Icons.local_gas_station_rounded),
                          label: 'Postos',
                        ),
                        NavigationDestination(
                          icon: Icon(Icons.star_border_rounded),
                          selectedIcon: Icon(Icons.star_rounded),
                          label: 'Benefícios',
                        ),
                        NavigationDestination(
                          icon: Icon(Icons.person_outline),
                          selectedIcon: Icon(Icons.person_rounded),
                          label: 'Perfil',
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            );
          },
        ),'''

if old_bottom not in text:
    raise SystemExit('Temporary fixed points strip not found')
text = text.replace(old_bottom, new_bottom, 1)

# Replace any older generated points component so the final layout is deterministic.
component_start = text.find('int _nextBenefitGoal(int pontosUsuario) {')
anchor = 'class _Dot extends StatelessWidget {'
component_end = text.find(anchor)
if component_start != -1 and component_end != -1 and component_end > component_start:
    text = text[:component_start] + text[component_end:]

component = r'''int _nextBenefitGoal(int pontosUsuario) {
  const int faixaBeneficio = 2000;
  final safePoints = pontosUsuario < 0 ? 0 : pontosUsuario;
  return ((safePoints ~/ faixaBeneficio) + 1) * faixaBeneficio;
}

class _PointsCard extends StatelessWidget {
  const _PointsCard({
    required this.pontosUsuario,
    required this.metaProximoBeneficio,
    required this.onViewStatement,
  });

  final int pontosUsuario;
  final int metaProximoBeneficio;
  final VoidCallback onViewStatement;

  String _formatPoints(int value) {
    final safe = value < 0 ? 0 : value;
    final raw = safe.toString();
    final buffer = StringBuffer();
    for (var i = 0; i < raw.length; i++) {
      if (i > 0 && (raw.length - i) % 3 == 0) buffer.write('.');
      buffer.write(raw[i]);
    }
    return buffer.toString();
  }

  @override
  Widget build(BuildContext context) {
    final safePoints = pontosUsuario < 0 ? 0 : pontosUsuario;
    final pontosRestantes = (metaProximoBeneficio - safePoints).clamp(0, metaProximoBeneficio);
    final progresso = metaProximoBeneficio <= 0
        ? 0.0
        : (safePoints / metaProximoBeneficio).clamp(0.0, 1.0).toDouble();

    return AspectRatio(
      aspectRatio: 1600 / 704,
      child: ClipRRect(
        borderRadius: BorderRadius.circular(18),
        child: LayoutBuilder(
          builder: (context, constraints) {
            final w = constraints.maxWidth;
            final h = constraints.maxHeight;
            return Stack(
              fit: StackFit.expand,
              children: [
                Image.asset(
                  'assets/images/points_card_base.jpg',
                  fit: BoxFit.cover,
                  alignment: Alignment.center,
                ),
                Positioned(
                  left: w * .275,
                  top: h * .155,
                  width: w * .385,
                  height: h * .56,
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Text(
                        'Seus pontos',
                        maxLines: 1,
                        style: TextStyle(
                          color: AppColors.muted,
                          fontSize: h * .075,
                          fontWeight: FontWeight.w500,
                          height: 1.0,
                        ),
                      ),
                      SizedBox(height: h * .025),
                      Text(
                        _formatPoints(safePoints),
                        maxLines: 1,
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: h * .155,
                          fontWeight: FontWeight.w900,
                          height: .95,
                        ),
                      ),
                      SizedBox(height: h * .055),
                      Flexible(
                        child: Text(
                          'Faltam ${_formatPoints(pontosRestantes)} pontos para o próximo benefício!',
                          maxLines: 2,
                          overflow: TextOverflow.ellipsis,
                          style: TextStyle(
                            color: AppColors.muted,
                            fontSize: h * .063,
                            fontWeight: FontWeight.w500,
                            height: 1.18,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
                Positioned(
                  left: w * .685,
                  top: h * .135,
                  width: w * .275,
                  height: h * .225,
                  child: Material(
                    color: Colors.transparent,
                    child: InkWell(
                      onTap: onViewStatement,
                      borderRadius: BorderRadius.circular(h * .10),
                      child: Center(
                        child: FittedBox(
                          fit: BoxFit.scaleDown,
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            children: [
                              Text(
                                'Ver extrato',
                                style: TextStyle(
                                  color: Colors.white,
                                  fontSize: h * .070,
                                  fontWeight: FontWeight.w700,
                                ),
                              ),
                              SizedBox(width: w * .008),
                              Icon(
                                Icons.chevron_right_rounded,
                                size: h * .12,
                                color: Colors.white,
                              ),
                            ],
                          ),
                        ),
                      ),
                    ),
                  ),
                ),
                Positioned(
                  left: w * .275,
                  right: w * .145,
                  bottom: h * .105,
                  height: h * .052,
                  child: ClipRRect(
                    borderRadius: BorderRadius.circular(999),
                    child: Stack(
                      fit: StackFit.expand,
                      children: [
                        Container(color: const Color(0xFF092B78)),
                        FractionallySizedBox(
                          alignment: Alignment.centerLeft,
                          widthFactor: progresso,
                          child: Container(
                            decoration: const BoxDecoration(
                              color: Color(0xFFE91746),
                              borderRadius: BorderRadius.all(Radius.circular(999)),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            );
          },
        ),
      ),
    );
  }
}

'''

if anchor not in text:
    raise SystemExit('Widget anchor not found')
text = text.replace(anchor, component + anchor, 1)

path.write_text(text, encoding='utf-8')
